### ISSUE TITLE
New AADInternals scripts running to avoid error

### ISSUE THREAD

**Issue by RangerJavelin** [Azure/SimuLand#14]
[Orginal document]
4. On the same elevated PowerShell session, run the following commands to install AADInternals if it is not installed yet:
```
Install-Module –Name AADInternals –RequiredVersion 0.4.8 -Force 
Import-Module –Name AADInternals 
```

I got errors when I run it but to get over the error by running the above scripts, I can use these instead
```
Install-Module -Name AADInternals -RequiredVersion 0.4.8
Import-Module AADInternals
```

**Comment by Cyb3rWard0g** [comment]
Hello @RangerJavelin ! Thank you for reaching out and sharing what worked for you. Quick question. do you remember the error message that you got? It would help us to know exactly why the -force command did not work. If you still have the error message, it will be helpful to document it before pushing a hot-fix to the repo. Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
I tested it again and it worked fine. 
![image](https://user-images.githubusercontent.com/9653181/127074875-e3ecf59f-37d2-47e0-897b-f175634e0844.png)
