### ISSUE TITLE
AAD diagnostic setting build failure

### ISSUE THREAD

**Issue by jorlamd** [Azure/SimuLand#20]
Hi!

Getting this error while trying to deploy the template, azureSentinel2Go succeeds and all else seems to build normally. Wondering if you had encountered it before and what I may be missing, google is not cooperating too much on this one!

```
AADConnector-7bolxxjg3amwg
microsoft.aadiam/diagnosticSettings
NotFound
Operation details


{
    "status": "Failed",
    "error": {
        "code": "OperationNotFound",
        "message": "Path: '/subscriptions/.../resourcegroups/azhybrid/providers/microsoft.aadiam/diagnosticSettings/AADConnector-7bolxxjg3amwg' is not supported"
    }
}

```

**Comment by jorlamd** [comment]
Never mind, was attempting to deploy at resource group level with resources at tenant level. using az deploy tenant (as specified in the instructions) works well.

**Comment by Cyb3rWard0g** [comment]
Thank you for the update @jorlamd ! Happy to hear the instructions helped! Thank you for testing the project.
