### ISSUE TITLE
CreateADForest Conflict Error

### ISSUE THREAD

**Issue by Dabuek** [Azure/SimuLand#24]
Hi,

I am getting a conflict error on the deployment script and work what the issue is, just wondering if theres something obvious I am missing:

I have uploaded the full error txt.

![image](https://user-images.githubusercontent.com/13871600/156317104-6914ba5c-a424-4f49-8869-8c90b144e7e8.png)

Should the CreateADForest Resource exist in both deployWinADFS and CreateADForest like this?

![image](https://user-images.githubusercontent.com/13871600/156317332-f5ab3ff6-1c3e-4706-9f20-34526dbe88ad.png)

![image](https://user-images.githubusercontent.com/13871600/156317223-c55f350d-36fc-40af-b722-4ef36d4a8412.png)

[Error.txt](https://github.com/Azure/SimuLand/files/8167651/Error.txt)

**Comment by Dabuek** [comment]
Also, when I log into the DC I can see it _has_ made my domain forest, but hasnt added any of the users other than the adfs and local admin

**Comment by Cyb3rWard0g** [comment]
Hello @Dabuek ! Thank you for letting me know about this issue.  Very interesting. Let me deploy the on-prem environment in my environment to see if I can replicate the error. Have you already tried to run it one more time?

**Comment by Dabuek** [comment]
I believe I found the issue, I am not using a .com domain - I have a '.co.uk' domain - For example 'simuland.co.uk'

I think therefore the .split is causing an issue;

https://github.com/OTRF/Blacksmith/blob/ee0f5b8eecdb87092c4f36e30cce49db3063fef2/resources/scripts/powershell/dsc/active-directory/Create-AD.ps1#L134

I did a local test using this and the output looks correct

```
 $DomainName1,$DomainName2,$DomainName3 = ($using:domainFQDN).split('.')
 $ParentPath = "DC=$DomainName1,DC=$DomainName2,DC=$DomainName3 "
```

**Comment by Dabuek** [comment]
I think this code would fix my issue, I need to rerun it... but would be good to have it be more dynamic for other TLD's if it is the problem.

https://github.com/Dabuek/Blacksmith/blob/master/resources/scripts/powershell/dsc/active-directory/Create-AD.ps1

**Comment by Cyb3rWard0g** [comment]
Ahh makes sense. Yeah, that would do it. Let me do some testing with similar domains and see if we can get to a more dynamic approach in here. Sorry for the inconvenience.

**Comment by Cyb3rWard0g** [comment]
Hello @Dabuek ! This seems to be working now with the following change: https://github.com/OTRF/Blacksmith/blob/master/resources/scripts/powershell/dsc/active-directory/Create-AD.ps1#L28-L30 

Thank you for opening this issue. Feel free to re-open it if you still have the same issue.
