### ISSUE TITLE
Invalid content link

### ISSUE THREAD

**Issue by Sar4D** [Azure/SimuLand#28]
Hello, there seems to be an error for the link mentionned below in my picture.
I did go to the github repository and it seems like it has been changed 3 days ago.
The new links are : (Directory changed from ASimRegistery to  ASimRegisteryEvent)

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimRegistry**Event**/ARM/vimRegistryEventMicrosoftWindowsEvent/vimRegistryEventMicrosoftWindowsEvent.json

and

https://github.com/Azure/Azure-Sentinel/blob/master/Parsers/ASimRegistry**Event**/ARM/vimRegistryEventMicrosoftSysmon/vimRegistryEventMicrosoftSysmon.json

Is it possible to update the deployment json file to point to the correct link? 

![error](https://user-images.githubusercontent.com/100158491/159522709-7589ea61-5883-4f4e-bb95-cb1c2e5814d9.JPG)

**Comment by Cyb3rWard0g** [comment]
Hello @Sar4D ! Thank you very much for letting me know!  I will change that right now
