### ISSUE TITLE
incorrect uri to Import Identity Workbook

### ISSUE THREAD

**Issue by swiftsolves-msft** [Azure/SimuLand#31]
{
    "status": "Failed",
    "error": {
        "code": "InvalidContentLink",
        "message": "Unable to download deployment content from 'https://raw.githubusercontent.com/Azure/SimuLand/main/2_deploy/aadHybridIdentityADFS/linkedtemplates/IdentityWorkbookARM.json'. The tracking Id is '387c21cf-d5e9-49ab-b1a6-f8dbdb487447'. Please see https://aka.ms/arm-deploy for usage details."
    }
}

**Comment by Cyb3rWard0g** [comment]
Thank you @swiftsolves-msft !
