### ISSUE TITLE
Issue on page /environments/aadHybridIdentityADFS/README.html

### ISSUE THREAD

**Issue by eepyaich** [Azure/SimuLand#34]
The command listed at the bottom of the "Elevate Account Access" section didn't work for me (I received an "argument --assignee-object-id: expected one argument" error).  I think this is because the "az ad signed-in-user" command didn't return an "objectId", just an "Id".  [I'm using azure CLI version 2.39.0]

I guess that replacing the following:

az role assignment create --scope '/' --role 'Owner' --assignee-object-id $(az ad signed-in-user show --query **objectId**) --assignee-principal-type User

with:

az role assignment create --scope '/' --role 'Owner' --assignee-object-id $(az ad signed-in-user show --query **Id**) --assignee-principal-type User

is the correct fix, but it would be good for someone more familiar with the lab to confirm.

**Comment by Cyb3rWard0g** [comment]
With azure cli 2.24.2, ObjectId works

![image](https://user-images.githubusercontent.com/9653181/224120617-7de10a12-1102-4663-ad9a-e343ed142071.png)

**Comment by Cyb3rWard0g** [comment]
welp. Az CLI 2.46 does not like Upper case Id. 
![image](https://user-images.githubusercontent.com/9653181/224122741-30ed6b5e-87c0-4d44-b787-b0b073d29a70.png)

**Comment by Cyb3rWard0g** [comment]
I believe the following would be better to avoid "Id" case. 

```powershell
az ad signed-in-user show | ConvertFrom-Json | Select -ExpandProperty Id
```
