### ISSUE TITLE
Broken Link on page addCredentialsToApplication.md

### ISSUE THREAD

**Issue by michaelhidalgo** [Azure/SimuLand#4]
This Article [Add Credentials to Application ](https://github.com/Azure/SimuLand/blob/main/3_simulate_detect/persistence/addCredentialsToApplication.md#microsoft-365-hunting)
as s broken link to **[Credentials were added to an Azure AD application after 'Admin Consent' permissions granted [Solorigate]](https://github.com/microsoft/Microsoft-365-Defender-Hunting-Queries/blob/master/Persistence/CredentialsAddAfterAdminConsentedToApp%5BSolorigate%5D.md)**

**Comment by Cyb3rWard0g** [comment]
Hello @michaelhidalgo !

Thank you for the heads up, I see the link was updated after writing that part of the document. I will fix it in the following commit in a few mins.
